config/routes.rb
Rails.application.routes.draw do

  resources :tasks

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:name, :description)
  end

  def set_task
    @task = Task.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.submit %>
<% end %>

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>
<br>
<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>Tasks#index</h1>
<% @tasks.each do |task| %>
  <h2><%= link_to task.name, task_path(task) %></h2>
  <p><%= task.description %></p>
  <h4><%= link_to "Delete", task_path(task),
    method: :delete,
    data: { confirm: "Are you sure?" } %>
  <h4>
  <h4><%= link_to "Edit", edit_task_path(task) %></h4>
<% end %>

<h4><%= link_to "New task", new_task_path %></h4>

app/views/tasks/new.html.erb
<h1>Tasks#new</h1>
<br>
<%= render 'form' %>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<h2><%= @task.name %></h2>
<p><%= @task.description %></p>
<h3><%= link_to "Voltar", tasks_path %></h3>
<%= link_to "Delete", task_path(@task),
  method: :delete,
  data: { confirm: "Are you sure?" } %>